### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by daniktheboss** [mhsjlw/potion#1]
Sorry for opening issue but Idk how else to txt u. So how's spiffy? I see not good and I have a project pycraft mcpe server with python. Works for 0.13.1 but needs update and more features implemented. I need help. Thanks

**Comment by mhsjlw** [comment]
Hmm. Spiffy is in a tight spot at the moment. I recommend you join our Gitter chat for more details.

**Comment by daniktheboss** [comment]
I see

**Comment by mhsjlw** [comment]
https://gitter.im/spiffy/spiffy, I'll look into PyCraft and see what I can do, but this isn't the place to talk about it.
